// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJmqucJrTlN8lqv-tUIML4GYymKpW_JQ',
    appId: '1:474640885275:web:f1ba5e05e6f4c35555fabe',
    messagingSenderId: '474640885275',
    projectId: 'querocafe-qc',
    authDomain: 'querocafe-qc.firebaseapp.com',
    storageBucket: 'querocafe-qc.appspot.com',
    measurementId: 'G-EX0GJKPG53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxv2lMDzBaKM-cijm_ykfKxHm3fAIQJ4',
    appId: '1:474640885275:android:2de866223d0e196055fabe',
    messagingSenderId: '474640885275',
    projectId: 'querocafe-qc',
    storageBucket: 'querocafe-qc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDVkQKsHwTiskeYxthgd16VToZmRIzqfg',
    appId: '1:474640885275:ios:d8dfb38e901cde1755fabe',
    messagingSenderId: '474640885275',
    projectId: 'querocafe-qc',
    storageBucket: 'querocafe-qc.appspot.com',
    iosClientId: '474640885275-a2qm1g8nkvev35b1eptf20p9eapmc97g.apps.googleusercontent.com',
    iosBundleId: 'br.dev.zeduardu.querocafeMobapp',
  );
}
